# Generated by Django 6.0.2 on 2026-02-19 16:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='next_check_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
