# Generated by Django 6.0.2 on 2026-02-27 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_product_next_check_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='next_check_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
