# Generated by Django 6.0.2 on 2026-02-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_product_next_check_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='checked_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product', 'checked_at'], name='tracker_pri_product_017da6_idx'),
        ),
    ]
